### ISSUE TITLE
Webcolors install fails due to syntax error

### ISSUE THREAD

**Issue by mrzacharycook** [ubernostrum/webcolors#1]
I have a Raspberry Pi with Raspbian and Python 3.2.3.  When I attempt to install Webcolors with pip, or manually download the tar.gz and run the install script, I get the following error:

running install
running build
running build_py
running install_lib
creating /usr/local/lib/python3.2
creating /usr/local/lib/python3.2/dist-packages
copying build/lib/webcolors.py -> /usr/local/lib/python3.2/dist-packages
byte-compiling /usr/local/lib/python3.2/dist-packages/webcolors.py to webcolors.cpython-32.pyc
  File "/usr/local/lib/python3.2/dist-packages/webcolors.py", line 41
    SUPPORTED_SPECIFICATIONS = (u'html4', u'css2', u'css21', u'css3')
                                       ^
SyntaxError: invalid syntax

running install_egg_info
Writing /usr/local/lib/python3.2/dist-packages/webcolors-1.5.egg-info

Any ideas?

**Comment by ubernostrum** [comment]
`webcolors` explicitly does not support Python 3.2, and never will.

Supported Python versions are [listed in the documentation](http://webcolors.readthedocs.org/en/1.5/faq.html#what-versions-of-python-are-supported).

**Comment by mrzacharycook** [comment]
Thank you for the quick feedback!
