### ISSUE TITLE
Feature request: Function to convert to floats from 0 to 1

### ISSUE THREAD

**Issue by paulmelnikow** [ubernostrum/webcolors#11]
Hi there! And thanks for this useful library!

I'm using this with pycollada, which wants RGB values as arrays of three floats from 0.0 to 1.0.

Would you be interested in a pull request to a function for exposing color values as rgb floats?

**Comment by ubernostrum** [comment]
This module really only does the RGB formats of the HTML/CSS specs, and I'm unaware of any such format in one of those specs.

**Comment by paulmelnikow** [comment]
Right. However, worth noting that [WebGL uses them](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendColor).

**Comment by bersbersbers** [comment]
I would love this, too. This is easily the best colors library I know for Python, and I feel it's somewhat artificial to restrict its use for the web.
