### ISSUE TITLE
deprecation of mapping of colornames breaks tikzplotlib

### ISSUE THREAD

**Issue by JasonGross** [ubernostrum/webcolors#20]
tikzplotlib uses the color mapping [to compute closest matching color names](https://github.com/nschloe/tikzplotlib/blob/450712b4014799ec5f151f234df84335c90f4b9d/src/tikzplotlib/_color.py#L29-L45):
```python
def _get_closest_colour_name(rgb):
    match = None
    mindiff = 1.0e15
    for h, name in webcolors.CSS3_HEX_TO_NAMES.items():
        r = int(h[1:3], 16)
        g = int(h[3:5], 16)
        b = int(h[5:7], 16)

        diff = (rgb[0] - r) ** 2 + (rgb[1] - g) ** 2 + (rgb[2] - b) ** 2
        if diff < mindiff:
            match = name
            mindiff = diff

        if mindiff == 0:
            break

    return match, mindiff
```
this seems broken by the leatest release of webcolors due to https://github.com/ubernostrum/webcolors/commit/68ba427417b6065684a162f1484c45886a401a85.  Would it be possible to add enough support to the official API to allow this sort of computation?  (Being able to get a set of the supported named colors, for example, would be enough.)

**Comment by ubernostrum** [comment]
I can look into whether it's worth adding an API for lists of color names, but given that the affected project seems to be completely unmaintained I'm not sure any new API in `webcolors` will help that project's users :/

**Comment by JasonGross** [comment]
I'm kinda maintaining a series of patches on it at https://github.com/JasonGross/tikzplotlib / https://pypi.org/project/tikzplotlib-patched, so I'd update the webcolors use there at least

**Comment by ubernostrum** [comment]
So if there were a function with, say, this signature:

```python
def names(spec: str = webcolors.CSS3) -> list[str]
    ...
```

would that suit your purpose? Do you also need a way to bulk-retrieve the corresponding color values?

**Comment by JasonGross** [comment]
> would that suit your purpose?

Yes, that should work!



> Do you also need a way to bulk-retrieve the corresponding color values?

No, doing `{name: name_to_rgb(name) for name in names()}` should give the relevant values, right?

**Comment by ubernostrum** [comment]
@JasonGross tell me if https://github.com/ubernostrum/webcolors/commit/dee9d4668976805427bd23dd1f5ddbec52cf547f works for you and I'll work on getting a release out.

**Comment by JasonGross** [comment]
@ubernostrum https://github.com/ubernostrum/webcolors/commit/dee9d4668976805427bd23dd1f5ddbec52cf547f looks like it should work, thank you!

**Comment by ubernostrum** [comment]
Release 24.8.0 is on PyPI now.
