### ISSUE TITLE
Feature request: get color group instead of color name

### ISSUE THREAD

**Issue by anacosmina** [ubernostrum/webcolors#9]
Hi,

I've recently used this module to get the name of an RGB color, but was only interested in getting generic names (like the group names from [here](https://www.w3schools.com/colors/colors_groups.asp)). I needed to write a dictionary for converting from color name to color group.

What about extending the functionality of `get_colour_name` by adding a `group` flag? If needed, I could totally help with that.

Best,
Cosmina

**Comment by ubernostrum** [comment]
This module only supports what the HTML/CSS standards support. The grouping you suggest does not appear to be part of any standard.
